[remote_servers]
student-app ansible_host=127.0.0.1 ansible_user=kathir ansible_connection=local

[remote_servers:vars]
ansible_python_interpreter=/usr/bin/python3
deploy_dir=/home/kathir/student-management
app_jar=student-management.jar
app_port=8080
app_name=student-management
